[window]
padding.x = 8
padding.y = 8
startup_mode = "Maximized"

[font]
size = 10.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style  = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style  = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style  = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style  = "Regular"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

